platform :osx, '10.13'

target 'AQI macOS' do
  use_frameworks!
  pod 'Marshal'
  pod 'Moya', '<= 12.0.1'
  pod 'RealmSwift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxOptional',  '~> 3.6.0'
  pod 'RxGesture'
  pod 'RxRealm'
  pod 'SnapKit'
end
